Repository bodhiproject/bodhi-ui, pull requests merged in 2018-06, with the labels that each got.

#645 fix 书籍货币 to 数字货币
  package-lock.json
  src/languageProvider/locales/zh-Hans.json
Labels: UX/UI, bug

#704 554 loading animation onscroll + mobx
  .eslintrc.json
  package.json
  src/components/BackButton/index.js
  src/components/InfiniteScroll/index.js
  src/components/Loading/index.js
  src/components/Loading/styles.js
  src/config/theme.js
  src/helpers/utility.js
  src/languageProvider/locales/en_US.json
  src/languageProvider/locales/ko-KR.json
  src/languageProvider/locales/zh-Hans.json
  src/redux/Graphql/saga.js
  src/scenes/AllEvents/index.js
  src/scenes/AllEvents/styles.js
  src/scenes/App/components/Loader/index.js
  src/scenes/App/globalHub.js
  src/scenes/App/index.js
  src/scenes/Dashboard/components/TopActions/index.js
  src/stores/AllEventsStore.js
  src/stores/AppStore.js
  src/stores/PubSubStore.js
  src/stores/UiStore.js
  src/stores/WalletStore.js
  src/stores/models/Oracle.js
  src/stores/models/Topic.js
  yarn.lock
Labels: enhancement, feature

#702 Tooltip reward
  package-lock.json
  src/components/RewardTooltipContent/index.js
  src/components/RewardTooltipContent/styles.js
  src/languageProvider/locales/en_US.json
  src/languageProvider/locales/ko-KR.json
  src/languageProvider/locales/zh-Hans.json
  src/scenes/App/components/Loader/index.js
  src/scenes/Event/scenes/topic.js
  src/style/base.less
  yarn.lock
Labels: feature
